### ISSUE TITLE
mat does not want to initialize zero length matrix

### ISSUE THREAD

**Issue by faide** [PacktPublishing/Machine-Learning-With-Go#4]
this line https://github.com/PacktPublishing/Machine-Learning-With-Go/blob/d39c4f4cf229e9f8ed4ae91b25fd3c48bf758b59/Chapter08/building_a_simple_nn/example1/myprogram.go#L107

leads to a panic:

```panic: mat: zero length in matrix dimension```

seems like the mat library does not like initializing zero length matrixes...

**Comment by faide** [comment]
for the record if someone wonders, you can correct all occurrences of 

```golang
something := mat.NewDense(0, 0, nil) 
```
by rewriting them as

```golang
something := new(mat.Dense)
```
and the program will be able to compile

**Comment by gaurav-packt** [comment]
Thanks for sharing your feedback, it'll surely assist the readers to overcome the issue.
